const optionsList = [
  { title: 'Metroid Ball Taken', bitIndex: 0 },
  { title: 'Missile Container (Brinstar)', bitIndex: 1 },
  { title: 'Red Door (Long Beam)', bitIndex: 2 },
  { title: 'Red Door (Tourian Bridge)', bitIndex: 3 },
  { title: 'Energy Tank (Brinstar)', bitIndex: 4 },
  { title: 'Red Door (bombs)', bitIndex: 5 },
  { title: 'Bombs Taken', bitIndex: 6 },
  { title: 'Red Door (Ice Beam Brinstar)', bitIndex: 7 },
  { title: 'Missile Container (Brinstar)', bitIndex: 8 },
  { title: 'Energy Tank (Brinstar)', bitIndex: 9 },
  { title: 'Red Door (Varia)', bitIndex: 10 },
  { title: 'Varia Taken', bitIndex: 11 },
  { title: 'Energy Tank', bitIndex: 12 },
  { title: 'Missile Container (Norfair)', bitIndex: 13 },
  { title: 'Missile Container (Norfair)', bitIndex: 14 },
  { title: 'Red Door (Ice Beam Norfair)', bitIndex: 15 },
  { title: 'Missile Container (Norfair)', bitIndex: 16 },
  { title: 'Missile Container (Norfair)', bitIndex: 17 },
  { title: 'Missile Container (Norfair)', bitIndex: 18 },
  { title: 'Missile Container (Norfair)', bitIndex: 19 },
  { title: 'Missile Container (Norfair)', bitIndex: 20 },
  { title: 'Missile Container (Norfair)', bitIndex: 21 },
  { title: 'Missile Container (Norfair)', bitIndex: 22 },
  { title: 'Red Door (High Jump boots)', bitIndex: 23 },
  { title: 'High Jump Boots Taken', bitIndex: 24 },
  { title: 'Red Door (Screw Attack)', bitIndex: 25 },
  { title: 'Screw Attack Taken', bitIndex: 26 },
  { title: 'Missile Container (Norfair)', bitIndex: 27 },
  { title: 'Missile Container (Norfair)', bitIndex: 28 },
  { title: 'Red Door (Wave Beam)', bitIndex: 29 },
  { title: 'Energy Tank (Norfair)', bitIndex: 30 },
  { title: 'Missile Container (Norfair)', bitIndex: 31 },
  { title: 'Red Door (Kraid\'s Lair)', bitIndex: 32 },
  { title: 'Missile Container (Kraid\'s Lair)', bitIndex: 33 },
  { title: 'Missile Container (Kraid\'s Lair)', bitIndex: 34 },
  { title: 'Red Door (Kraid\'s Lair)', bitIndex: 35 },
  { title: 'Energy Tank (Kraid\'s Lair)', bitIndex: 36 },
  { title: 'Red Door (Kraid\'s Lair)', bitIndex: 37 },
  { title: 'Red Door (Kraid\'s Lair)', bitIndex: 38 },
  { title: 'Missile Container (Kraid\'s Lair)', bitIndex: 39 },
  { title: 'Missile Container (Kraid\'s Lair)', bitIndex: 40 },
  { title: 'Red Door (Kraid\'s Room)', bitIndex: 41 },
  { title: 'Energy Tank (Kraid\'s Room)', bitIndex: 42 },
  { title: 'Missile Container (Ridley\'s Lair)', bitIndex: 43 },
  { title: 'Red Door (Ridley\'s Lair)', bitIndex: 44 },
  { title: 'Energy Tank (Ridley\'s Lair)', bitIndex: 45 },
  { title: 'Missile Container (Ridley\'s Lair)', bitIndex: 46 },
  { title: 'Yellow Door (in Ridley\'s Room)', bitIndex: 47 },
  { title: 'Energy Tank (Room Behind Ridley)', bitIndex: 48 },
  { title: 'Missile Container (Ridley\'s Lair)', bitIndex: 49 },
  { title: 'Yellow Door (Tourian)', bitIndex: 50 },
  { title: 'Red Door (Tourian)', bitIndex: 51 },
  { title: 'Red Door (Tourian)', bitIndex: 52 },
  { title: 'Zebetite 1 Defeated', bitIndex: 53 },
  { title: 'Zebetite 2 Defeated', bitIndex: 54 },
  { title: 'Zebetite 3 Defeated', bitIndex: 55 },
  { title: 'Zebetite 4 Defeated', bitIndex: 56 },
  { title: 'Zebetite 5 Defeated', bitIndex: 57 },
  { title: 'Mother Brain Defeated', bitIndex: 58 },
  { title: 'Unknown', bitIndex: 59 },
  { title: 'Unknown', bitIndex: 60 },
  { title: 'Unknown', bitIndex: 61 },
  { title: 'Unknown', bitIndex: 62 },
  { title: 'Unknown', bitIndex: 63 },
  { title: 'Start in Norfair', bitIndex: 64 },
  { title: 'Start in Kraid\'s Lair', bitIndex: 65 },
  { title: 'Start In Ridley\'s Lair', bitIndex: 66 },
  { title: 'Reset Bit', bitIndex: 67 },
  { title: 'Unknown', bitIndex: 68 },
  { title: 'Unknown', bitIndex: 69 },
  { title: 'Unknown', bitIndex: 70 },
  { title: 'Samus in Swimsuit', bitIndex: 71 },
  { title: 'Samus has bombs', bitIndex: 72 },
  { title: 'Samus has high jump boots', bitIndex: 73 },
  { title: 'Samus has Long Beam', bitIndex: 74 },
  { title: 'Samus has Screw Attack', bitIndex: 75 },
  { title: 'Samus has Metroid Ball', bitIndex: 76 },
  { title: 'Samus has Varia', bitIndex: 77 },
  { title: 'Samus has Wave Beam', bitIndex: 78 },
  { title: 'Samus has Ice Beam', bitIndex: 79 },
  { title: 'Missile Count +1', bitIndex: 80 },
  { title: 'Missile Count +2', bitIndex: 81 },
  { title: 'Missile Count +4', bitIndex: 82 },
  { title: 'Missile Count +8', bitIndex: 83 },
  { title: 'Missile Count +16', bitIndex: 84 },
  { title: 'Missile Count +32', bitIndex: 85 },
  { title: 'Missile Count +64', bitIndex: 86 },
  { title: 'Missile Count +128', bitIndex: 87 },
  { title: 'Game Age +1 Tick', bitIndex: 88 },
  { title: 'Game Age +2 Ticks', bitIndex: 89 },
  { title: 'Game Age +4 Ticks', bitIndex: 90 },
  { title: 'Game Age +8 Ticks', bitIndex: 91 },
  { title: 'Game Age +16 Ticks', bitIndex: 92 },
  { title: 'Game Age +32 Ticks', bitIndex: 93 },
  { title: 'Game Age +64 Ticks', bitIndex: 94 },
  { title: 'Game Age +128 Ticks', bitIndex: 95 },
  { title: 'Game Age +256 Ticks', bitIndex: 96 },
  { title: 'Game Age +512 Ticks', bitIndex: 97 },
  { title: 'Game Age +1024 Ticks', bitIndex: 98 },
  { title: 'Game Age +2048 Ticks', bitIndex: 99 },
  { title: 'Game Age +4096 Ticks', bitIndex: 100 },
  { title: 'Game Age +8192 Ticks', bitIndex: 101 },
  { title: 'Game Age +16384 Ticks', bitIndex: 102 },
  { title: 'Game Age +32768 Ticks', bitIndex: 103 },
  { title: 'Game Age +65536 Ticks', bitIndex: 104 },
  { title: 'Game Age +131072 Ticks', bitIndex: 105 },
  { title: 'Game Age +262144 Ticks', bitIndex: 106 },
  { title: 'Game Age +524288 Ticks', bitIndex: 107 },
  { title: 'Game Age +1048576 Ticks', bitIndex: 108 },
  { title: 'Game Age +2097152 Ticks', bitIndex: 109 },
  { title: 'Game Age +4194304 Ticks', bitIndex: 110 },
  { title: 'Game Age +8388608 Ticks', bitIndex: 111 },
  { title: 'Game Age +16777216 Ticks', bitIndex: 112 },
  { title: 'Game Age +33554432 Ticks', bitIndex: 113 },
  { title: 'Game Age +67108864 Ticks', bitIndex: 114 },
  { title: 'Game Age +134217728 Ticks', bitIndex: 115 },
  { title: 'Game Age +268435456 Ticks', bitIndex: 116 },
  { title: 'Game Age +536870912 Ticks', bitIndex: 117 },
  { title: 'Game Age +1073741824 Ticks', bitIndex: 118 },
  { title: 'Game Age +2147483648 Ticks', bitIndex: 119 },
  { title: 'Unknown', bitIndex: 120 },
  { title: 'Unknown', bitIndex: 121 },
  { title: 'Unknown', bitIndex: 122 },
  { title: 'Unknown', bitIndex: 123 },
  { title: 'Ridley Defeated', bitIndex: 124 },
  { title: 'Ridley Statue Raised', bitIndex: 125 },
  { title: 'Kraid Defeated', bitIndex: 126 },
  { title: 'Kraid Statue Raised', bitIndex: 127 },
];

export default optionsList;
